parameters:
    #@see CethyworksAnalyticsExtension
    cethyworks.analytics_tracker.class: Cethyworks\AnalyticsBundle\Listener\AnalyticsTrackerListener
    cethyworks.googleAnalytics_tracker.template: CethyworksAnalyticsBundle:Tracker:googleAnalytics.html.twig
    cethyworks.analytics_auto.template: CethyworksAnalyticsBundle:SegmentIo:analytics_auto.html.twig

services:
    kernel.listener.start.exercise:
        class: Cethyworks\AnalyticsBundle\Listener\Listener
        tags:
            - { name: kernel.event_listener, event: start.exercise, method: onExerciseStart }
            - { name: kernel.event_listener, event: ask.result, method: onAskResult }
            - { name: kernel.event_listener, event: security.interactive_login, method: onUserConnect }
            - { name: kernel.event_listener, event: exercise.ask_tip, method: onExerciseAskTip }
            - { name: kernel.event_listener, event: video.play, method: onVideoPlay }
        arguments: ["@initialize.listener.identify"]
            

    initialize.listener.identify:
        class: Cethyworks\AnalyticsBundle\Handler\AnalyticsHandler
        arguments: [%cethyworks_analytics.segmentIo.account_id%]
