parameters:
    cethyworks.analytics_tracker.class: Cethyworks\AnalyticsBundle\Listener\AnalyticsTrackerListener
    cethyworks.analytics_tracker.template: CethyworksAnalyticsBundle:Tracker:analytics.html.twig